### PR TITLE
adding pagination to stocks in home page

### PR DESCRIPTION
**Pull request by murradkh**
this PR includes:
1) added pagination to the home page
2)  changing the behavior of the thread-scheduler (which updates stocks values) to update constantly the focused page, where the user is looking at.
3) added the ability to quantify the number of stocks on the page with different values, and added a drop-down-button of home page "stocks per page".

-) @kamaql97 can you check to the changes I made near your changes, to make sure not breaking anything.

-) tests on the pagination on the server-side is not an easy task, the right place to test it is on the client-side, using tools like the selenium, that's we would use later as we discussed.

### CODE REVIEW

**Comment by kamalq97** [comment]
> @kamaql97 can you check to the changes I made near your changes, to make sure not breaking anything.

I looked at the code changes in the **views.py** file and I ran my unit tests on your code and there are no issues. When doing manual testing, I noticed that clicking the blue/red watchlist icon in the list always takes you back to the first page, but this issue should be solved after pull request #22 is merged. 

From a UI point of view, I am not sure why you decided to embed the "stocks per page" dropdown in the main website navbar; the dropdown is not relevant to every page on the website, so it should not always appear.

image 

I think its location should be within the content block of the home view '`index`'.

**Comment by Malak-abuthaa** [comment]
i think you did a great job , i see we can go for few improvement 

1. when clicking to the next page the rank start from 1 over again
2. some enhancement on design 
3. about the testing part and schedule job , we will ask Tommar about tmw

**Comment by murradkh** [comment]
> > @kamaql97 can you check to the changes I made near your changes, to make sure not breaking anything.
> 
> I looked at the code changes in the **views.py** file and I ran my unit tests on your code and there are no issues. When doing manual testing, I noticed that clicking the blue/red watchlist icon in the list always takes you back to the first page, but this issue should be solved after pull request #22 is merged.
> 
> From a UI point of view, I am not sure why you decided to embed the "stocks per page" dropdown in the main website navbar; the dropdown is not relevant to every page on the website, so it should not always appear.
> 
> image
> 
> I think its location should be within the content block of the home view '`index`'.

Agree with you
Fixed
Screenshot 2020-10-21 122504

**Comment by murradkh** [comment]
> i think you did a great job , i see we can go for few improvement
> 
> 1. when clicking to the next page the rank start from 1 over again
> 2. some enhancement on design
> 3. about the testing part and schedule job , we will ask Tommar about tmw

okay I will change the starting index according to the page

**Comment by murradkh** [comment]
> > i think you did a great job , i see we can go for few improvement
> > 
> > 1. when clicking to the next page the rank start from 1 over again
> > 2. some enhancement on design
> > 3. about the testing part and schedule job , we will ask Tommar about tmw
> 
> okay I will change the starting index according to the page
fixed
Screenshot 2020-10-21 143818

**Review by Malak-abuthaa — APPROVED** [review]
ready to merge 
good job

**Pull request merged**
