### PR TITLE
changing the design of pagination

### PR DESCRIPTION
**Pull request by murradkh**
refinning the pagination naviagation 
Screenshot 2020-11-14 131052

### CODE REVIEW

**Review by kamalq97 — CHANGES_REQUESTED** [review]
You are right in the sense that there is no need to show _every_ page number on the Home page, but I also think having only _one_ page number appear is very restrictive. 

If you want to redesign this, then consider having a link to the first and last page and the previous three and next three pages, similar to this:
image
[Django pagination example](https://docs.djangoproject.com/en/3.1/topics/pagination/#paginating-a-listview) (which you probably have seen before)

**Review by Malak-abuthaa — CHANGES_REQUESTED** [review]
i agree with kamal opinion , but you can solve it on the client side , use javascript code that render first , middle and the last page , and hide the others
please check this link 

https://stackoverflow.com/questions/46382109/limit-the-number-of-visible-pages-in-pagination/46385144

**Comment by murradkh** [comment]
> You are right in the sense that there is no need to show _every_ page number on the Home page, but I also think having only _one_ page number appear is very restrictive.
> 
> If you want to redesign this, then consider having a link to the first and last page and the previous three and next three pages, similar to this:
> image
> [Django pagination example](https://docs.djangoproject.com/en/3.1/topics/pagination/#paginating-a-listview) (which you probably have seen before)

got you, you right

**Comment by murradkh** [comment]
> i agree with kamal opinion , but you can solve it on the client side , use javascript code that render first , middle and the last page , and hide the others
> please check this link
> 
> https://stackoverflow.com/questions/46382109/limit-the-number-of-visible-pages-in-pagination/46385144

yes, it can also be done on the client-side, but I already have the code which rending the pagination design on the server-side ...

**Review by kamalq97 — APPROVED** [review]
Much better now! 👍

**Review by Malak-abuthaa — APPROVED** [review]
looks great , good job

**Pull request merged**
